<a href="https://colab.research.google.com/github/MoriMorou/GB_Python/blob/master/HW_Lesson_6_SLE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Решите линейную систему:
$$\begin{equation*}
\begin{vmatrix}
\mathbf{1}  ; \mathbf{2} ; \mathbf{3} \\
\mathbf{4} ; \mathbf{0} ; \mathbf{6} \\
\mathbf{7} ; \mathbf{8} ; \mathbf{9}
\end{vmatrix} * X = 
\begin{vmatrix}
\mathbf{12} \\
\mathbf{2} \\
\mathbf{1}
\end{vmatrix}
\end{equation*}$$

In [0]:
import numpy as np

In [0]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

In [11]:
det_A = np.linalg.det(A)

print(det_A)

59.999999999999986


 Как как определитель матрицы А не равен нулю мы можем найти решение СЛАУ 

In [15]:
X1 = np.linalg.solve(A, B)
X2 = np.dot(np.linalg.inv(A), B)
print(X1)
print(X2)

[-9.2         0.9         6.46666667]
[-9.2         0.9         6.46666667]


Проверка:

In [16]:
print(np.dot(A, X1))
print(np.dot(A, X2))

[12.  2.  1.]
[12.  2.  1.]



2. Найдите псевдорешение:

x + 2y – z = 1

3x – 4y = 7

8x – 5y + 2z = 12

2x – 5z = 7

11x +4y – 7z = 15