<a href="https://colab.research.google.com/github/MoriMorou/GB_Python/blob/master/Lesson_4_REVISED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Урок 4

# Матрицы и матричные операции. Часть 2

## Определитель матрицы

Рассмотрим произвольную квадратную матрицу порядка $n$:

$$A=\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{pmatrix}.$$


С каждой такой матрицей свяжем численную характеристику, называемую _определителем_, соответствующим этой матрице. 


Сразу заметим, что понятие определителя имеет смысл __только для квадратных матриц__.

Если порядок $n$ матрицы равен единице, то есть эта матрица состоит из одного элемента $a_{11}$, определителем, соответствующим такой матрице, назовем сам этот элемент.

Если порядок матрицы равен $2$, то есть матрица имеет вид

$$A=\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix},$$

то определителем второго порядка, соответствующим такой матрице, назовем число, равное 

$$a_{11}a_{22} - a_{12}a_{21}.$$

Словесно это правило можно сформулировать так: _определитель второго порядка, соответствующий матрице $A$, равен разности произведения элементов, стоящих на главной диагонали этой матрицы, и элементов, стоящих на ее побочной диагонали._

Определитель матрицы $A$ обозначается как $detA$, или $|A|$, то есть определитель второго порядка можно записать как

$$detA=|A|=\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$

Будем двигаться дальше и выясним понятие определителя для матриц порядка $n\geq2.$

Для этого введем понятие минора. _Минором_ любого элемента $a_{ij}$ матрицы $n$-го порядка назовем определитель порядка $n-1$, соответствующий матрице, которая получается из исходной матрицы путем вычеркивания $i$-й строки и $j$-го столбца (строки и столбца, на пересечении которых стоит элемент $a_{ij}$). Обозначать минор будем символом $M_{ij}$.

Определителем матрицы порядка $n$ назовем число, равное

$$detA=\begin{vmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{vmatrix} = 
\sum_{j=1}^{n}(-1)^{j+1}a_{1j}M_{1j}.$$

Эта формула представляет собой правило составления определителя порядка $n$ по элементам первой строки и минорам $M_{1j}$, являющимися определителями порядка $n-1$.

Заметим, что при $n=2$ правило совпадает с введенным ранее правилом получения определителя для матриц второго порядка: в этом случае миноры элементов первой строки имеют вид $M_{11}=a_{22}$, $M_{12}=a_{21}$.

__Теорема__

При любом произвольном номере строки $i~(i=1,2,...,n)$ для определителя порядка $n$ справедлива формула

$$detA = \sum_{j=1}^{n}(-1)^{i+j}a_{ij}M_{ij},$$

называемая _разложением этого определителя по $i$-й строке._

__Теорема__

При любом произвольном номере столбца $j~(j=1,2,...,n)$ для определителя порядка $n$ справедлива формула

$$detA = \sum_{i=1}^{n}(-1)^{i+j}a_{ij}M_{ij},$$

называемая _разложением этого определителя по $j$-му столбцу._

Таким образом, определитель может быть сформирован разложением как по произвольной строке исходной матрицы, так и по произвольному ее столбцу.

__Пример__

Вычислим определитель

$$\begin{vmatrix}
1 & 1 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{vmatrix}.$$

__Решение__

$$\begin{vmatrix}
1 & 2 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{vmatrix}=
1\cdot\begin{vmatrix}
1 & 4\\ 
3 & 6
\end{vmatrix}-
2\cdot\begin{vmatrix}
1 & 4\\ 
2 & 6
\end{vmatrix}+
1\cdot\begin{vmatrix}
1 & 1\\ 
2 & 3
\end{vmatrix}=1\cdot(1\cdot6-3\cdot4)-2\cdot(1\cdot6-2\cdot4)+1\cdot(1\cdot3-2\cdot1)=-6+4+1=-1.
$$

__Пример__

Найдем определитель матрицы 

$$A=\begin{pmatrix}
-1 & -4 & 0 & -2 \\ 
0 & 1 & 5 & 4 \\  
3 & 1 & 1 & 0 \\ 
-1 & 0 & 2 & 2\\ 
\end{pmatrix},$$

разложив его<br>
1) по элементам 2-го столбца;<br>
2) по элементам 3-й строки.

__Решение__

1. Разложение определителяя 4-го порядка по элементам 2-го столбца будет иметь вид

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & a_{14}\\ 
a_{21} & a_{22} & a_{23} & a_{24}\\  
a_{31} & a_{32} & a_{33} & a_{34} \\ 
a_{41} & a_{42} & a_{43} & a_{44}\\ 
\end{vmatrix} = 
(-1)^{1+2}a_{12}\begin{vmatrix}
a_{21} & a_{23} & a_{24}\\  
a_{31} & a_{33} & a_{34} \\ 
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + (-1)^{2+2}a_{22}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\  
a_{31} & a_{33} & a_{34} \\ 
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + (-1)^{3+2}a_{32}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\ 
a_{21} & a_{23} & a_{24}\\  
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + (-1)^{4+2}a_{42}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\ 
a_{21} & a_{23} & a_{24}\\  
a_{31} & a_{33} & a_{34} \\ 
\end{vmatrix}.$$

Таким образом, для матрицы $A$

$$\begin{vmatrix}
-1 & -4 & 0 & -2 \\ 
0 & 1 & 5 & 4 \\  
3 & 1 & 1 & 0 \\ 
-1 & 0 & 2 & 2\\ 
\end{vmatrix} = 4\begin{vmatrix}
0 & 5 & 4 \\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} + \begin{vmatrix}
-1 & 0 & -2\\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} - \begin{vmatrix}
-1 & 0 & -2\\ 
0 & 5 & 4\\  
-1 & 2 & 2 \\ 
\end{vmatrix} + 0.$$

Так задача нахождения определителя 4-го порядка сводится к нахождению трех определителей 3-го порядка. Вычислим первый, разложив по первой строке:

$$\begin{vmatrix}
0 & 5 & 4 \\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} = 
0\begin{vmatrix}
1 & 0\\  
2 & 2 \\ 
\end{vmatrix}
-5\begin{vmatrix}
3 & 0\\  
-1 & 2 \\ 
\end{vmatrix} + 
4\begin{vmatrix}
3 & 1\\  
-1 & 2\\ 
\end{vmatrix} = 0\cdot(1\cdot2-2\cdot0)
-5\cdot(3\cdot2 - (-1)\cdot 0) + 4\cdot(3\cdot2 - (-1)\cdot1) = -2.$$

Аналогично вычисляем 
$$\begin{vmatrix}
-1 & 0 & -2\\ 
3 & 1 & 0\\  
-1 & 2 & 2 \\ 
\end{vmatrix} = 
(-1)\begin{vmatrix}
1 & 0\\  
2 & 2 \\ 
\end{vmatrix} - 
0\begin{vmatrix}
3 & 0\\  
-1 & 2 \\ 
\end{vmatrix} + 
(-2)\begin{vmatrix}
3 & 1\\  
-1 & 2 \\ 
\end{vmatrix} = 
(-1)\cdot(1\cdot2-2\cdot0) - 0\cdot(3\cdot2-(-1)\cdot0) + (-2)\cdot(3\cdot2-(-1)\cdot1) = -16,$$

$$\begin{vmatrix}
-1 & 0 & -2\\ 
0 & 5 & 4\\  
-1 & 2 & 2 \\ 
\end{vmatrix} = 
(-1)\begin{vmatrix}
5 & 4\\  
2 & 2 \\ 
\end{vmatrix} - 
0\begin{vmatrix}
0 & 4\\  
-1 & 2 \\ 
\end{vmatrix} +
(-2)\begin{vmatrix}
0 & 5\\  
-1 & 2\\ 
\end{vmatrix} = 
(-1)\cdot(5\cdot2 - 2\cdot4) - 0\cdot(0\cdot2-(-1)\cdot4) + (-2)\cdot(0\cdot2-(-1)\cdot5) = -12.$$

Подставляя полученные значения определителей в исходное разложение, получим

$$|A| = 4\cdot(-2) + (-16) - (-12) = -12.$$

2. Разложение определителяя 4-го порядка по элементам 3-й строки будет иметь вид

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & a_{14}\\ 
a_{21} & a_{22} & a_{23} & a_{24}\\  
a_{31} & a_{32} & a_{33} & a_{34} \\ 
a_{41} & a_{42} & a_{43} & a_{44}\\ 
\end{vmatrix} =
(-1)^{3+1}a_{31}\begin{vmatrix}
a_{12} & a_{13} & a_{14}\\ 
a_{22} & a_{23} & a_{24}\\  
a_{42} & a_{43} & a_{44}\\ 
\end{vmatrix} + 
(-1)^{3+2}a_{32}\begin{vmatrix}
a_{11} & a_{13} & a_{14}\\ 
a_{21} & a_{23} & a_{24}\\  
a_{41} & a_{43} & a_{44}\\ 
\end{vmatrix} + 
(-1)^{3+3}a_{33}\begin{vmatrix}
a_{11} & a_{12} & a_{14}\\ 
a_{21} & a_{22} & a_{24}\\  
a_{41} & a_{42} & a_{44}\\ 
\end{vmatrix} +
(-1)^{3+4}a_{34}\begin{vmatrix}
a_{11} & a_{12} & a_{13}\\ 
a_{21} & a_{22} & a_{23}\\  
a_{41} & a_{42} & a_{43}
\end{vmatrix}.$$

Для матрицы $A$:

$$\begin{vmatrix}
-1 & -4 & 0 & -2 \\ 
0 & 1 & 5 & 4 \\  
3 & 1 & 1 & 0 \\ 
-1 & 0 & 2 & 2\\ 
\end{vmatrix} = 3\begin{vmatrix}
-4 & 0 & -2 \\ 
1 & 5 & 4 \\  
0 & 2 & 2\\ 
\end{vmatrix} -\begin{vmatrix}
-1 & 0 & -2 \\ 
0 & 5 & 4 \\  
-1 & 2 & 2\\ 
\end{vmatrix} + \begin{vmatrix}
-1 & -4 & -2 \\ 
0 & 1 & 4 \\  
-1 & 0 & 2\\ 
\end{vmatrix} - 0.$$

Найдем определители третьего порядка:

$$\begin{vmatrix}
-4 & 0 & -2 \\ 
1 & 5 & 4 \\  
0 & 2 & 2\\ 
\end{vmatrix} = (-4)\cdot(5\cdot2-2\cdot4) - 0\cdot(1\cdot2 - 0\cdot4) + (-2)\cdot(1\cdot2-0\cdot5)= -12,$$

$$\begin{vmatrix}
-1 & 0 & -2 \\ 
0 & 5 & 4 \\  
-1 & 2 & 2\\ 
\end{vmatrix} = (-1)\cdot(5\cdot2-2\cdot4) - 0\cdot(0\cdot2-(-1)\cdot4) + (-2)\cdot(0\cdot2-(-1)\cdot5)= -12,$$

$$\begin{vmatrix}
-1 & -4 & -2 \\ 
0 & 1 & 4 \\  
-1 & 0 & 2\\ 
\end{vmatrix} = (-1)\cdot(1\cdot2-0\cdot4) - (-4)\cdot(0\cdot2-(-1)\cdot4) + (-2)\cdot(0\cdot0-(-1)\cdot1) = 12.$$

Подставляя полученные значения определителей в исходное разложение, получим

$$|A| = 3\cdot(-12) - (-12) + 12 = -12.$$

### Выражение определителя непосредственно через его элементы

Установим формулу нахождения детерминанта $n$-го порядка непосредственно через его элементы (минуя миноры).

Для этого введем понятия перестановок и транспозиций на множестве.

_Перестановкой_ на множестве $S=\{1,2,3,...,n\}$ называется множество тех же чисел, упорядоченное некоторым образом:

$$\{1,2,3,4\}\Rightarrow\{3,4,1,2\}.$$

_Транспозицией_ называется такая перестановка, в которой переставлены местами только два элемента множества, в то время как остальные элементы остаются на своих местах:

$$\{1,2,3,4\}\Rightarrow\{\underline{4},2,3,\underline{1}\}.$$


Любую перестановку можно реализовать путем нескольких последовательных транспозиций. Например, перестановка $\{3,4,1,2\}$ представляет собой последовательность трех транспозиций:

$$\{\underline{1},2,\underline{3},4\}\Rightarrow\{3,\underline{2},1,\underline{4}\}\Rightarrow\{3,4,1,2\}.$$

Принято,что перестановка содержит __инверсию__ элементов $i_{j}$ и $i_{k}$, если $i_{j}>i_{k}$ при $j<k.$

Например, наша перестановка $\{3,4,1,2\}$ содержит четыре инверсии: 

- $3$ и $1$, так как число $3$ стоит слева от меньшего числа $1$, и по аналогии следующие: 
- $3$ и $2$; 
- $4$ и $1$;
- $4$ и $2$.

Число инверсий определяет __четность__ перестановки. То есть перестановка считается четной, если она содержит четное число инверсий и нечетной, если нечетное число.

_Для множества $S=\{1,2,3,...,n\}$ существует $n!$ различных перестановок._

__Пример__

Возьмем множество $\{1,2,3\}$. Оно будет содержать $3!=6$ перестановок:

$$\{1,2,3\}, \{2,1,3\}, \{2,3,1\}, \{3,2,1\}, \{3,1,2\}, \{1,3,2\}.$$

При этом:

- перестановки $\{1,2,3\}$, $\{2,3,1\}$ и $\{3,1,2\}$ будут являться четными;
- перестановки $\{2,1,3\}$, $\{3,2,1\}$ и $\{1,3,2\}$ будут являться нечетными.

__Вернемся к понятию определителя__

Возьмем квадратную матрицу $A$ $n$-го порядка (размера $n\times n$) и множество $\{k_{1}, k_{2}, ...,k_{n}\}$, являющееся некоторой перестановкой упорядоченного множества натуральных чисел $\{1,2,...,n\}$.

Рассмотрим произведение, содержащее $n$ матричных элементов, взятых по одному из каждой строки, составленное следующим образом:

$$a_{1k_{1}}a_{2k_{2}}...a_{nk_{n}}.$$



Первый множитель явлется элементом из первой строки и $k_{1}$ столбца, второй — из второй строки и $k_{2}$ столбца и т. д. 

Вспомним, что существует $n!$ различных перестановок $\{k_{1}, k_{2}, ...,k_{n}\}$ из индексов столбцов. Каждая из них будет формировать произведение указанного вида. Припишем каждому такому произведению знак $«+»$, если перестановка $\{k_{1}, k_{2}, ...,k_{n}\}$ четная, и $«-»$, если нечетная.

Чтобы описать это математически, введем выражение $P\{k_{1}, k_{2}, ...,k_{n}\}$, которое будет обозначать число инверсий в соответствующей перестановке. В этом случае удобно определять знак произведения таким образом:

$$(-1)^{P\{k_{1}, k_{2}, ...,k_{n}\}}=\begin{cases}
+1 & \text{ в случае четной перестановки, } \\ 
-1 & \text{ в случае нечетной перестановки. } 
\end{cases}$$

Сумма всех возможных произведений элементов матрицы $A$, описанных вышеуказанным образом, и будет являться определителем матрицы $A$:

$$detA=\sum_{\{k_{1}, k_{2}, ...,k_{n}\}}a_{1k_{1}}a_{2k_{2}}...a_{nk_{n}}(-1)^{P\{k_{1}, k_{2}, ...,k_{n}\}}.$$

Данное правило также можно вывести из формулы определения через миноры. С выводом можно ознакомиться в книге В. А. Ильина и Э. Г. Позняка «Линейная алгебра» из списка литературы.

В случае $n=2$ формула элементарно проверяется, если принять во внимание, что существует всего две перестановки множества $\{1,2\}$: $\{1,2\}$ и $\{2,1\}$, первая из которых является четной, вторая — нечетной. Таким образом, получим

$$\begin{vmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{vmatrix}=a_{11}a_{22} - a_{12}a_{21}.$$

В NumPy определитель матрицы вычисляется с помощью функции `numpy.linalg.det(a)`, где `a` — матрица.

__Пример__

Найдем определители из примеров выше с помощью Python:

In [0]:
import numpy as np

In [0]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 1]
 [1 1 4]
 [2 3 6]]
Определитель:
-1


In [0]:
b = np.array([[-1, -4, 0, -2], [0, 1, 5, 4], [3, 1, 1, 0], [-1, 0, 2, 2]])
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[-1 -4  0 -2]
 [ 0  1  5  4]
 [ 3  1  1  0]
 [-1  0  2  2]]
Определитель:
-12


### Свойства определителей

__1.__ Определитель транспонированной матрицы равен определителю исходной:

$$detA^{T}=detA.$$

__2.__ Умножение строки или столбца матрицы на число $\lambda$ приведет к умножению определителя матрицы на то же число. 

- Доказательство этого свойства элементарно, так как, исходя из формулы определителя, множитель из этой строки будет в каждом из слагаемых при нахождении определителя разложением по этой строке/столбцу, что равнозначно его умножению на это число.

__3.__ Перестановка любых двух строк или столбцов матрицы приводит к изменению знака определителя.

- Это происходит из-за того, что дополнительная транспозиция меняет четность перестановки.

__4.__ Если матрица имеет нулевую строку или столбец, то определитель равен нулю. 

- По аналогии с пунктом 2: в каждом из слагаемых будет множитель — элемент из этой строки (столбца), а значит, все они обнулятся.

__5.__ Если две строки (столбца) матрицы равны между собой, то определитель этой матрицы равен нулю. 

- Согласно свойству 3, перестановка двух строк (столбцов) приводит к смене знака определителя. С другой стороны, если строки равны, то определитель измениться не должен. Оба эти условия одновременно выполняются, только когда определитель равен нулю:

$$detA=-detA \Rightarrow detA=0.$$

__6.__ Если две строки (столбца) матрицы линейно зависимы, то определитель этой матрицы равен нулю.

- Согласно свойству 2, множитель строки (столбца) можно вынести за знак определителя. Вынеся таким образом множитель пропорциональности, мы получим матрицу, имеющую две одинаковых строки (столбца). Согласно свойству 5, определитель такой матрицы равен нулю.

__7.__ Определитель матрицы треугольного вида равен произведению элементов, стоящих на ее главной диагонали:

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
0 & a_{22} & a_{23} & \cdots & a_{2n}\\ 
0 & 0 & a_{33} & \cdots & a_{3n}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
0 & 0 & 0 & \cdots & a_{nn}
\end{vmatrix}=a_{11}\cdot a_{22}\cdot ... \cdot a_{nn}.$$

__8.__ Если матрица $A$ ортогональна, то определитель такой матрицы 

$$detA = \pm1.$$

__9.__ Для двух квадратных матриц одинакового размера

$$det(AB)=detA\cdot detB.$$

__10.__ Если элементы строки (столбца) матрицы являются результатом суммы, то

$$\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1}+b_{k1} & a_{k2}+b_{k2} & a_{k3}+b_{k3} & \cdots & a_{kn}+b_{kn}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
a_{1n} & a_{2n} & a_{3n} & \cdots & a_{nn}
\end{vmatrix}=
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1} & a_{k2} & a_{k3} & \cdots & a_{kn}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
a_{1n} & a_{2n} & a_{3n} & \cdots & a_{nn}
\end{vmatrix}+
\begin{vmatrix}
a_{11} & a_{12} & a_{13} & \cdots & a_{1n}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
b_{k1} & b_{k2} & b_{k3} & \cdots & b_{kn}\\ 
\cdots & \cdots & \cdots & \ddots & \cdots\\ 
a_{1n} & a_{2n} & a_{3n} & \cdots & a_{nn}
\end{vmatrix}.$$

__11.__ Если к одной из строк матрицы прибавить другую, умноженную на число, ее определитель не изменится:

$$\begin{vmatrix}
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{i1} & a_{i2} & a_{i3} & \cdots & a_{in}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1}& a_{k2}& a_{k3} & \cdots & a_{kn}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
\end{vmatrix}=
\begin{vmatrix}
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{i1} & a_{i2} & a_{i3} & \cdots & a_{in}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
a_{k1}+\lambda a_{i1} & a_{k2}+\lambda a_{i2}& a_{k3}+\lambda  a_{i3} & \cdots & a_{kn}+\lambda  a_{in}\\ 
\cdots & \cdots & \cdots & \cdots & \cdots\\ 
\end{vmatrix}.$$

- Такой определитель можно будет представить в виде суммы двух, первый из которых будет равен исходному, а второй будет содержать линейно зависимые строки, в связи с чем обратится в ноль.

__Пример__

Вычислим определитель

$$\begin{vmatrix}
2 & -4 & 1\\ 
-3 & 2 & 5\\ 
1 & 2 & 3
\end{vmatrix}.$$

__Решение__

Так как при прибавлении к строке другой строки, умноженной на число, определитель не меняется, мы можем осуществить некоторые преобразования для обнуления максимального количества элементов:

- преобразуем первую строку, вычтя третью, умноженную на 2;
- преобразуем вторую строку, прибавив к ней третью, умноженную на 3.

Получим:

$$\begin{vmatrix}
2 & -4 & 1\\ 
-3 & 2 & 5\\ 
1 & 2 & 3
\end{vmatrix}=
\begin{vmatrix}
0 & -8 & -5\\ 
0 & 8 & 14\\ 
1 & 2 & 3
\end{vmatrix}.$$

Далее поменяем местами первую и третью строки (при этом знак определителя изменится, по свойству 3):

$$-\begin{vmatrix}
1 & 2 & 3\\
0 & 8 & 14\\ 
0 & -8 & -5
\end{vmatrix}.$$

И прибавим к третьей строке вторую:

$$-\begin{vmatrix}
1 & 2 & 3\\
0 & 8 & 14\\ 
0 & 0 & 9
\end{vmatrix}.$$

Мы получили матрицу треугольного вида, определитель которой равен произведению диагональных элементов:

$$-\begin{vmatrix}
1 & 2 & 3\\
0 & 8 & 14\\ 
0 & 0 & 9
\end{vmatrix}=-1\cdot8\cdot9=-72.$$

Проверим с помощью Python:

In [0]:
a = np.array([[2, -4, 1], [-3, 2, 5], [1, 2, 3]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -4  1]
 [-3  2  5]
 [ 1  2  3]]
Определитель:
-72


__Определение__

Матрица называется _сингулярной_, или _вырожденной_, если ее определитель равен нулю.

## Ранг матрицы

Введем понятие минора $k$-го порядка.

_Минором $k$-го порядка_ матрицы $A$ размера $m\times n$ будем называть определитель $k$-го порядка ($k$ не превосходит меньшее из $m$ и $n$) с элементами, лежащими на пересерчении любых $k$ строк и любых $k$ столбцов матрицы $A$.

__Определение__

Предположим, что хотя бы один из элементов матрицы $A$ отличен от нуля. Тогда найдется целое положительное число $r$, такое, что:<br>
1) у матрицы $A$ имеется минор $r$-го порядка, отличный от нуля;<br>
2) любой минор порядка $r+1$ и выше равен нулю.

Число $r$, удовлетворяющее этим требованиям, назовем _рангом матрицы $A$_ и обозначим $rankA$, а минор $r$-го порядка — _базисным минором_.

Иными словами, ранг матрицы — это порядок ее максимального невырожденного (или базисного) минора.

__Определение__

_Строчным рангом матрицы_ называется максимальное число линейно независимых строк этой матрицы.

_Столбцовым рангом матрицы_ называется максимальное число линейно независимых столбцов этой матрицы.

__Теорема__

_Строчный ранг матрицы всегда совпадает с столбцовым и равен максимальному размеру ее невырожденного минора._

При работе с рангом матрицы важно знать, какие преобразования матриц не приводят к изменению их ранга:

- транспонирование;

- перестановка местами двух строк (столбцов);

- умножение всех элементов строки (столбца) на число, не равное нулю;

- прибавление ко всем элементам строки (столбца) соответствующих элементов другой строки (столбца);

- выбрасывание нулевой строки (столбца);

- выбрасывание строки (столбца), являющейся линейной комбинацией других строк (столбцов).

__Пример__

Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

В контексте машинного обучения эта характеристика особенно важна, так как наличие линейно зависимых строк в обучающей выборке приводит к избыточности информации и усложнению модели. Такие строки из обучающих выборок можно удалять без ущерба для точности получаемой модели, осуществляя сжатие данных без потерь.

В NumPy ранг матрицы вычисляется с помощью функции `numpy.linalg.matrix_rank(a)`, где `a` — матрица.

Кроме прочего, с помощью ранга матрицы можно проверять векторы на линейную зависимость.

Имея несколько векторов, мы можем составить из них матрицу, где эти векторы будут являться строками или столбцами. Векторы будут линейно независимы тогда и только тогда, когда ранг полученной матрицы совпадет с числом векторов. 

In [0]:
x = [1, 2, 3]
y = [2, 2, 2]
z = [3, 3, 3]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


## Понятие обратной матрицы

Матрица $B$ называется _правой обратной матрицей_ к $A$, если 

$$AB=E,$$

где $E$ — единичная матрица.

Матрица $C$ называется _левой обратной матрицей_ к $A$, если 

$$CA=E.$$

__Утверждение__

Если для матрицы $A$ существуют левая и правая обратные матрицы, то они совпадают между собой.

__Теорема__

Для того, чтобы для матрицы $A$ существовали левая и правая обратные матрицы, необходимо и достаточно, чтобы       определитель матрицы $A$ был отличен от нуля.

Таким образом, в случае невырожденных матриц можно опускать термины «левая» и «правая», и говорить просто о матрице, _обратной по отношению к матрице_ $A$, и обозначать ее символом $A^{-1}$:

$$A^{-1}A=AA^{-1}=E,$$

где $E$ — единичная матрица.

Если для матрицы $A$ существует обратная матрица, то она единственна.

_Если матрица вырождена, то у нее нет обратной матрицы._

- __Доказательство__

Допустим, матрица $A$ вырождена, то есть $detA=0$, и для нее существует обратная матрица $A^{-1}$. Тогда из соотношения $A\cdot A^{-1}=E$ получим, что $detA\cdot detA^{-1}=detE=1$, откуда следует, что $detA\neq0$, что противоречит условию. То есть, если у матрицы есть обратная, значит, матрица невырождена. Что и требовалось доказать.

__Нахождение обратной матрицы (метод присоединенной матрицы)__

Для ввода алгоритма нахождения обратной матрицы к матрице $A$ введем понятие алгебраического дополнения.

_Алгебраическим дополнением_ элемента $a_{ij}$ квадратной матрицы $A$ порядка $n$ называют минор $M_{ij}$, умноженный на $(-1)^{i+j}$, и обозначают $A_{ij}$:

$$A_{ij}=(-1)^{i+j}M_{ij}.$$

Алгоритм нахождения обратной матрицы следующий:

1. Найти определитель матрицы $A$ и убедиться, что $detA\neq0$;

2. Составить алгебраические дополнения $A_{ij}$ для каждого элемента матрицы $A$ и записать матрицу $A^{*}=(A_{ij})$ из найденных алгебраических дополнений.

3. Записать обратную матрицу, определенную по формуле 

$$A^{-1}=\frac{1}{detA}\cdot A^{*T}.$$

Матрицу $A^{*T}$ часто называют _присоединенной (союзной)_ к матрице $A$.

__Пример__

Найдем обратную матрицу для матрицы

$$A = \begin{pmatrix}
1 & 2 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{pmatrix}.$$

__Решение__

1. Найдем определитель:

$$\begin{vmatrix}
1 & 2 & 1\\ 
1 & 1 & 4\\ 
2 & 3 & 6
\end{vmatrix} = -6 + 4 + 1 = -1. $$

2. Найдем алгебраические дополнения для каждого элемента:

$$A_{11}=(-1)^{2}\begin{vmatrix}
1 & 4\\ 
3 & 6
\end{vmatrix} = -6,~
A_{12}=(-1)^{3}\begin{vmatrix}
1 & 4\\ 
2 & 6
\end{vmatrix} = 2,~
A_{13}=(-1)^{4}\begin{vmatrix}
1 & 1\\ 
2 & 3
\end{vmatrix} = 1,$$
$$A_{21}=(-1)^{3}\begin{vmatrix}
2 & 1\\ 
3 & 6
\end{vmatrix} = -9,~
A_{22}=(-1)^{4}\begin{vmatrix}
1 & 1\\ 
2 & 6
\end{vmatrix} = 4,~
A_{23}=(-1)^{5}\begin{vmatrix}
1 & 2\\ 
2 & 3
\end{vmatrix} = 1,$$
$$A_{31}=(-1)^{4}\begin{vmatrix}
2 & 1\\ 
1 & 4\\ 
\end{vmatrix} = 7,~
A_{32}=(-1)^{5}\begin{vmatrix}
1 & 1\\ 
1 & 4
\end{vmatrix} = -3,~
A_{33}=(-1)^{6}\begin{vmatrix}
1 & 2\\ 
1 & 1\\ 
\end{vmatrix} = -1.$$

Полученная матрица из алгебраических дополнений:

$$A^{*} = \begin{pmatrix}
-6 & 2 & 1\\ 
-9 & 4 & 1\\ 
7 & -3 & -1
\end{pmatrix},~
A^{*T} = \begin{pmatrix}
-6 & -9 & 7\\ 
2 & 4 & -3\\ 
1 & 1 & -1
\end{pmatrix}.$$

3. Используя формулу из алгоритма, получим

$$A^{-1} = \frac{1}{(-1)}\cdot \begin{pmatrix}
-6 & -9 & 7\\ 
2 & 4 & -3\\ 
1 & 1 & -1
\end{pmatrix} = \begin{pmatrix}
6 & 9 & -7\\ 
-2 & -4 & 3\\ 
-1 & -1 & 1
\end{pmatrix}.$$

В NumPy обратные матрицы вычисляются с помощью функции `numpy.linalg.inv(a)`, где `a` — матрица.

In [0]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=float)
b = np.linalg.inv(a)

print(f'Матрица A:\n{a}\n')
print(f'Матрица B, обратная к A:\n{b}\n')
print(f'Матрица AB (должна быть единичной):\n{a.dot(b)}')

Матрица A:
[[1. 2. 1.]
 [1. 1. 4.]
 [2. 3. 6.]]

Матрица B, обратная к A:
[[ 6.  9. -7.]
 [-2. -4.  3.]
 [-1. -1.  1.]]

Матрица AB (должна быть единичной):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Практическое задание

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

## Литература

1. Ильин В. А., Позняк Э. Г. Линейная алгебра: Учеб. для вузов. — 6-е изд. — М.: Физматлит, 2005.
2. Форсайт Дж., Молер К. Численное решение систем линейных алгебраических уравнений. — М.: Мир, 1969.
3. Кострикин А. И., Манин Ю. И. Линейная алгебра и геометрия. Учеб. пособие для вузов. — 2-е изд. — М.: Наука, Главная редакция физико-математической литературы, 1986.

## Дополнительные материалы:

1. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

2. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

3. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)