In [1]:
import numpy as np

Data base (shop)

In [2]:
products = np.array(['broad', 'milk', 'cream'])
products

array(['broad', 'milk', 'cream'], dtype='<U5')

In [27]:
price = np.array([40, 80, 70])
price

array([40, 80, 70])

In [28]:
price[products == 'broad']

array([40])

In [29]:
customers = np.array(['Bob', 'Alice', 'Joe'])
customers

array(['Bob', 'Alice', 'Joe'], dtype='<U5')

In [30]:
# строки - покупатели
# поля - продукты

In [31]:
history = np.array([[1, 2, 1],
                    [2, 3, 0],
                    [0, 1, 4]])
history

array([[1, 2, 1],
       [2, 3, 0],
       [0, 1, 4]])

In [32]:
# сколько каждый потратил денег

In [33]:
sum_history = history * price
sum_history

array([[ 40, 160,  70],
       [ 80, 240,   0],
       [  0,  80, 280]])

In [34]:
# сумма денег по полукателям
# 0 = строки
# 1 = стролбцы

In [35]:
sum_history.sum()

950

In [36]:
sum_history.sum(axis=1).reshape((-1, 1))

array([[270],
       [320],
       [360]])

In [37]:
# сумма по продуктам

In [38]:
sum_history.sum(axis=0)

array([120, 480, 350])

In [39]:
# среднее значение (сколько на одного покупателя)
sum_history.mean(axis=0)

array([ 40.        , 160.        , 116.66666667])

In [41]:
# медиана по продуктам (средина ряда, если четное кол-во, то среднее арифметическое двух в центре0
np.median(sum_history, axis=0)

array([ 40., 160.,  70.])