In [18]:
import numpy as np

In [3]:
a = [i for i in range(10)]

In [4]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
b = np.array(a)

In [7]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Создаем список типа numpy

In [8]:
c = np.array([i for i in range(14)])

In [9]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

Узнаем какой тип у объекта

In [11]:
type(c)

numpy.ndarray

Задаем какой тип данных должен быть в списке

In [14]:
c = np.array(a, dtype=float)

In [15]:
old_array = [1, 2, 3, 5.5]

In [20]:
new_array_int = np.array(old_array, dtype=int)

In [21]:
new_array_int

array([1, 2, 3, 5])

In [18]:
new_array_float = np.array(old_array, dtype=float)

In [19]:
new_array_float

array([1. , 2. , 3. , 5.5])

In [22]:
new_array_str = np.array(old_array, dtype=str)

In [23]:
new_array_str

array(['1', '2', '3', '5.5'], dtype='<U3')

In [25]:
new_array_str[3]

'5.5'

In [28]:
b.ndim

1

In [30]:
b.shape

(10,)

#### 2D array

In [19]:
a = np.array([[0, 1, 2, 4],
     [3, 4, 5, 4],
     [6, 7, 8, 9]])

In [46]:
a

array([[0, 1, 2, 4],
       [3, 4, 5, 4],
       [6, 7, 8, 9]])

In [47]:
a.shape

(3, 4)

In [48]:
a.size

12

In [49]:
a[2][2]

8

In [50]:
a[2, 2]

8

In [52]:
a[0:2, 0:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
a[:2, :3]

array([[0, 1, 2],
       [3, 4, 5]])

In [54]:
a[1:, 2:]

array([[5, 4],
       [8, 9]])

In [55]:
c = a[1:, 2:]

In [56]:
c

array([[5, 4],
       [8, 9]])

In [57]:
c[1, 1] = 13

In [58]:
c

array([[ 5,  4],
       [ 8, 13]])

In [59]:
a

array([[ 0,  1,  2,  4],
       [ 3,  4,  5,  4],
       [ 6,  7,  8, 13]])

Если мы хотим что бы массив "с" стал уникальным его нужно копировать

In [60]:
c = a[1:, 2:].copy()

In [61]:
c

array([[ 5,  4],
       [ 8, 13]])

Data types in numpy

In [23]:
f32 = np.array([1., 2., 3.], dtype=np.float32)

In [24]:
f32

array([1., 2., 3.], dtype=float32)

In [27]:
f64 = np.array([1., 2., 3.], dtype=np.float64)

In [28]:
f64

array([1., 2., 3.])

In [29]:
int32 = np.array([1., 2., 3.], dtype=np.int32)

In [30]:
int32

array([1, 2, 3], dtype=int32)

In [31]:
int64 = np.array([1., 2., 3.], dtype=np.int64)

In [32]:
int64

array([1, 2, 3])