In [1]:
import numpy as np

Data base

In [2]:
features = np.array(['Rooms', 'Square', 'KitchenSquare'])
features

array(['Rooms', 'Square', 'KitchenSquare'], dtype='<U13')

In [3]:
flat_id = np.array([112, 113, 115, 205])

In [ ]:
# строки квартиры
# столбы признаки квартир

In [4]:
flats = np.array([[1, 35, 8],
                 [1, 37, 10],
                 [2, 45, 11],
                 [3, 62, 12]])
flats

array([[ 1, 35,  8],
       [ 1, 37, 10],
       [ 2, 45, 11],
       [ 3, 62, 12]])

In [5]:
flats[flat_id== 205]

array([[ 3, 62, 12]])

In [6]:
flats[flat_id == 205, features =='Rooms']

array([3])

In [7]:
flats[3, 0]

3

In [8]:
# цены в мил руб
price = np.array([3.5, 3.8, 5.2, 7.2])
price

array([3.5, 3.8, 5.2, 7.2])

In [9]:
price = price.reshape((-1, 1))
price

array([[3.5],
       [3.8],
       [5.2],
       [7.2]])

Объединение массивов (hstack)

In [ ]:
flats2 = np.hstack([flats, price])
flats2

array([[ 1. , 35. ,  8. ,  3.5],
       [ 1. , 37. , 10. ,  3.8],
       [ 2. , 45. , 11. ,  5.2],
       [ 3. , 62. , 12. ,  7.2]])