In [1]:
import numpy as np

#### Выбор данных из массива

In [3]:
a = np.random.randint(0, 20, 10)
a

array([13, 13,  7,  0, 10,  2, 12,  1, 11, 10])

In [4]:
# фильтруем массив (только числа больше 10)
a[a > 10]

array([13, 13, 12, 11])

In [5]:
# больее сложный фильтр (& - знак аперсанта или логическое И)
a[(a > 10) & (a % 2 == 0)]

array([12])

In [7]:
a[(a > 10) | (a % 3 == 0)]

array([13, 13,  0, 12, 11])

**numpy.where**

In [8]:
a

array([13, 13,  7,  0, 10,  2, 12,  1, 11, 10])

In [9]:
# Первый вариант применения
# возвращаем индексы чисел, удовлетворяющих условию
np.where(a > 10)

(array([0, 1, 6, 8]),)

In [12]:
# Второй вариант применения
a = [1, 4, 7]
b = [9, 2, 5]

In [13]:
# Если в условии true, то берем элемет из массива а, a если false, то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

#### Сортировка

In [14]:
a = np.array([[1, 3, 9, 9],
              [5, 0, 1, 5],
              [2, 7, 3, 5]])

In [15]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [60]:
a.argsort(axis=0)

array([[0, 1, 0, 1],
       [1, 2, 2, 0],
       [2, 0, 1, 2]])

In [62]:
a[:, 0].argsort()

array([0, 1, 2])

In [18]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

#### Случайное перемешивание массивов

In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# inplace - на месте
np.random.shuffle(a)
a

array([6, 4, 0, 3, 5, 2, 9, 1, 7, 8])

In [22]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
# inplace - на месте (перемешиваются только строки)
np.random.shuffle(a)
a

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2],
       [ 3,  4,  5]])

#### Метематические действия с массивами

Применение математической функции ко всему массиву

In [30]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Алгорифм по основанию е
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [32]:
# Экспонента
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [33]:
a.sum()

21

In [34]:
a.sum(axis=0)

array([5, 7, 9])

In [35]:
a.sum(axis=1)

array([ 6, 15])

In [36]:
10 * a

array([[10, 20, 30],
       [40, 50, 60]])

По элементное (не матричное) умножение

In [37]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Broadcasting(на примере сложения)

In [43]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

1й случай - совпадает только число столбцов

In [44]:
b = np.array([1, 2])

In [45]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

2й случай - совпадает только число строк

In [48]:
c = np.array([[1], [2], [3]])

In [49]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

#### Основные статистические функции

In [51]:
a = np.random.randint(0, 12, (3, 4))
a

array([[3, 7, 1, 7],
       [3, 3, 3, 3],
       [7, 5, 1, 9]])

In [52]:
a.min()

1

In [53]:
# min для каждого столбца
a.min(axis=0)

array([3, 3, 1, 3])

In [54]:
# max для каждого строки
a.max(axis=1)

array([7, 3, 9])

In [55]:
# среднее значение
a.mean(axis=0)

array([4.33333333, 5.        , 1.66666667, 6.33333333])

In [56]:
# средне квадратичное отклонение
a.std(axis=0)

array([1.88561808, 1.63299316, 0.94280904, 2.49443826])

#### Запись и чтение массива из файла

In [57]:
np.save('a.npy', a)

In [59]:
b = np.load('a.npy')
b

array([[3, 7, 1, 7],
       [3, 3, 3, 3],
       [7, 5, 1, 9]])