In [1]:
import numpy as np

#### Автоматическое создание массивов

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [15]:
np.arange(0, 5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

**numpy.linspace** - то же самое, но нужно учитывать, что правая граница (9.9) будет включена. Вместо шага указываем нужное число элементов.

In [16]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

**numpy.logspace** - обе границы также включены, но это не сами числ, а степени числа 10

In [17]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

#### Генерация случайных чисел 

**numpy.random.sample** - случайные числа с равномерным распределением в промежутке [0.0, 1.0]

In [19]:
np.random.sample()

0.8482150864125929

In [20]:
np.random.sample(3)

array([0.24370885, 0.51008951, 0.73613663])

In [22]:
np.random.sample((2, 3))

array([[0.87597993, 0.2155055 , 0.30692688],
       [0.40200276, 0.93315212, 0.12938902]])

3D массив (напримерб массив можно использовать для изображний с высотой 48, шириной 64, и значением яркости 3х цветов для каждого пикселя)

In [24]:
np.random.sample((48, 64, 3))

array([[[0.20230585, 0.36926633, 0.81109136],
        [0.98641002, 0.82588679, 0.83184391],
        [0.21289604, 0.77593151, 0.15391646],
        ...,
        [0.69924849, 0.04338151, 0.76009605],
        [0.32900133, 0.72627573, 0.76137284],
        [0.76966525, 0.86596003, 0.75235135]],

       [[0.25623813, 0.13726413, 0.30099302],
        [0.59555481, 0.27594647, 0.79729643],
        [0.19760492, 0.25657455, 0.73465669],
        ...,
        [0.9683702 , 0.46140532, 0.88212298],
        [0.10162439, 0.55552127, 0.97362417],
        [0.98168579, 0.84908703, 0.32062787]],

       [[0.57877021, 0.65904698, 0.63761703],
        [0.56679223, 0.9376214 , 0.80536754],
        [0.50585749, 0.30962771, 0.42057012],
        ...,
        [0.85798064, 0.64484662, 0.62284697],
        [0.43506975, 0.14229001, 0.7335939 ],
        [0.51682503, 0.99988529, 0.99139444]],

       ...,

       [[0.34205467, 0.0922664 , 0.76636577],
        [0.59689551, 0.80724659, 0.40094929],
        [0.69430102, 0

**np.random.randn** - случайное число с нормальным распределением (среднее значение 0б среднеквадратичное отклонение = 1)

In [25]:
np.random.randn(10)

array([-0.10573572,  0.40643211,  0.99418432,  1.58092228, -0.32991778,
        0.75710589,  0.08199018, -0.86540361, -1.22229967,  0.18055559])

In [26]:
np.random.randn(3, 4)

array([[ 8.46003717e-01,  1.81100874e+00, -7.80814731e-01,
        -5.01439529e-01],
       [ 1.95701350e-03, -1.73451307e+00,  4.53871389e-01,
        -3.00077551e+00],
       [-6.50158347e-02, -7.43162452e-03,  8.99767755e-02,
        -6.24041950e-01]])

**np.random.randint** - массив целых чисел (10 элементов от 0 до 100)

In [27]:
np.random.randint(0, 100, 10)

array([69, 57, 90, 61, 62, 61, 64, 56,  1,  8])

In [28]:
np.random.randint(0, 10, (3, 4))

array([[1, 7, 0, 6],
       [9, 9, 1, 2],
       [3, 9, 7, 1]])

**np.random. choice** - случайный выбор эелемента 

In [31]:
v = np.array([1, 3, 5, 6, 7, 8, 9, 0])

In [33]:
np.random.choice(v)

8

In [34]:
np.random.choice(v, 3)

array([8, 3, 5])

**numpy.random.seed()** - инициализация генератора случайных чисел (Может использоваться для последующей воспроизводимости, то есть будут генерироваться те же числа, если установить одинаковый seed)

In [35]:
np.random.seed(42)

In [38]:
np.random.randint(0, 10, 3)

array([2, 6, 7])

#### Изменение формы массива