#### Операции с векторами

In [2]:
import numpy as np

In [5]:
a = np.array([0, 1, 2, 3, 4])

In [6]:
b = np.array([5, 6, 7, 8, 9])

In [7]:
a.size

5

In [8]:
a.shape

(5,)

#### Сложение векторов

In [9]:
c = a + b

In [10]:
c

array([ 5,  7,  9, 11, 13])

Отличие в python

In [11]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [12]:
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Еще один способ сложения

In [13]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

Вычитание векторов

In [18]:
a = np.array([5, 4, 3, 2, 1])
b = np.array([1, 2, 3, 4, 5])

In [19]:
d = b - a
d

array([-4, -2,  0,  2,  4])

In [21]:
e = np.subtract(a, b)
e

array([ 4,  2,  0, -2, -4])

In [22]:
a.shape == b.shape

True

Умножение вектора на скаляр

In [23]:
a = np.array([5, 4, 3, 2, 1])
a

array([5, 4, 3, 2, 1])

In [24]:
c = a * 2
c

array([10,  8,  6,  4,  2])

In [27]:
c = a.dot(2)
c

array([10,  8,  6,  4,  2])

In [28]:
a.dot(2)

array([10,  8,  6,  4,  2])

In [29]:
np.dot(2, a)

array([10,  8,  6,  4,  2])

In [30]:
np.multiply(2, a)

array([10,  8,  6,  4,  2])

In [25]:
c = a * -10
c

array([-50, -40, -30, -20, -10])

In [26]:
c = a * 0.5
c

array([2.5, 2. , 1.5, 1. , 0.5])

Скарлярное произведение векторов

In [42]:
m = np.array([1, 2, 3])
n = np.array([4, 5, 6])

In [43]:
m.shape == n.shape

True

In [48]:
sp = m[0] * n[0] + m[1] * n[1] + m[2] * n[2]
sp

32

In [50]:
m @ n

32

#### Операции над матрицами

In [54]:
A = np.array([[0, 1], 
              [2, 3], 
              [4, 5]])

In [55]:
B = np.array([[6, 7], 
              [8, 9], 
              [10, 11]])

In [56]:
A.shape == B.shape

True

In [57]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [58]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [59]:
C = B - A
C

array([[6, 6],
       [6, 6],
       [6, 6]])

In [60]:
C = np.subtract(B, A)
C

array([[6, 6],
       [6, 6],
       [6, 6]])

Умножение матрецы на скаляр

In [68]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [69]:
y = x * 3
y

array([[ 3,  6],
       [ 9, 12]])

In [70]:
y = np.dot(x, 3)
y

array([[ 3,  6],
       [ 9, 12]])