#### Умножение матриц

In [1]:
import numpy as np

In [15]:
a = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

In [16]:
b = np.array([[7, 8, 9, 10], 
              [11, 12, 13, 14]])

Делаем проверку что число столбцов А = числу сторок В

In [12]:
a.shape[1] == b.shape[0]

True

In [13]:
a.shape, b.shape

((3, 2), (2, 4))

In [17]:
c = np.dot(a, b)
c

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [18]:
c.shape

(3, 4)

In [19]:
c[0, 0]

29

#### Модуль numpy.linalg; возведение матрицы в квадрат

In [20]:
m = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [21]:
m_square = np.dot(m, m)
m_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [22]:
n_square = np.linalg.matrix_power(m, 2)
n_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

#### Создание единичной матрицы

In [23]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Умножение единичной матрица на обычную (получаем исходную матрицу

In [25]:
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

In [26]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [27]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [28]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

Транспонирование матрицы

In [30]:
A = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

In [31]:
At = np.transpose(A)
At

array([[1, 3, 5],
       [2, 4, 6]])

In [32]:
At = A.transpose()
At

array([[1, 3, 5],
       [2, 4, 6]])

In [33]:
At = A.T
At

array([[1, 3, 5],
       [2, 4, 6]])

Пример

In [42]:
x = np.array([[0, 1], 
              [3, 4], 
              [2, 6]])

In [50]:
y = np.array([[1, 2], 
              [3, 4], 
              [3, 4], 
              [5, 5]])

In [51]:
yt = y.T
yt

array([[1, 3, 3, 5],
       [2, 4, 4, 5]])

In [52]:
y.shape[1] == yt.shape[0]

True

In [53]:
np.dot(x, yt)

array([[ 2,  4,  4,  5],
       [11, 25, 25, 35],
       [14, 30, 30, 40]])

#### Вычисление определителя и ранга матрицы

In [55]:
m = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [56]:
np.linalg.det(m)

0.0

In [57]:
np.linalg.matrix_rank(m)

2

In [64]:
n = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [65]:
np.linalg.det(n)

85.99999999999997

In [66]:
np.linalg.matrix_rank(n)

3

Вычисление обратной матрицы

In [67]:
n = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [68]:
n_inv = np.linalg.inv(n)
n_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [69]:
n_inv_inv = np.linalg.inv(n_inv)
n_inv_inv

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])