## Матрицы и векторы
### Основные операции с векторами и матрицами

In [2]:
import numpy as np

#### Что такое матрица?
Матрица — математический объект, записываемый в виде прямоугольной таблицы элементов, например — целых или действительных чисел.

Матрица представляет собой совокупность строк и столбцов, на пересечении которых находятся её элементы. 

Количество строк и столбцов задает размер матрицы.
## $A = \left(
\begin{array}{cccc}
a_{00} & a_{01} & \ldots & a_{0n}\\
a_{10} & a_{11} & \ldots & a_{1n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{m0} & a_{m1} & \ldots & a_{mn}
\end{array}
\right)$

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -1, 12]], float)
print(a)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [ 0. -1. 12.]]


In [4]:
print(a[2, 1])

8.0


In [5]:
print(a.shape)

(4, 3)


#### Операции с матрицами

In [6]:
b = a * 2
print(b)

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]
 [ 0. -2. 24.]]


In [7]:
c = a + 1
print(c)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]
 [ 1.  0. 13.]]


In [8]:
d = c + b
print(d)

[[ 4.  7. 10.]
 [13. 16. 19.]
 [22. 25. 28.]
 [ 1. -2. 37.]]


In [9]:
d = np.subtract(b, c)
print(d)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [-1. -2. 11.]]


In [10]:
print(b - c)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [-1. -2. 11.]]


## Транспонирование матрицы
## $F =  D^T $

In [11]:
f = d.transpose()
print(d)

print("")
print(f)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [-1. -2. 11.]]

[[ 0.  3.  6. -1.]
 [ 1.  4.  7. -2.]
 [ 2.  5.  8. 11.]]


#### Умножение матриц
### $G =  D \cdot F$
### $g_{i j} =   d_{i 0} \cdotp f_{0 j} + d_{i 1} \cdotp f_{1 j} + d_{i 2} \cdotp f_{2 j} = \sum_{k=0}^{n-1} d_{i k} \cdotp f_{k j}$

In [12]:
i, j = 0, 2
d[i, 0] * f[0, j] + d[i, 1] * f[1, j] + d[i, 2] * f[2, j]

23.0

In [13]:
g = np.dot(f, d)
print(g)
d.shape, f.shape

[[ 46.  56.  52.]
 [ 56.  70.  56.]
 [ 52.  56. 214.]]


((4, 3), (3, 4))

#### Единичная и нулевая матрица
### $A \cdot E = E \cdot A = A$
### $A \cdot O = O \cdot A = O$
### $E =
\begin{pmatrix}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{pmatrix}
$
### $O =
\begin{pmatrix}
0 & 0 & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{pmatrix}
$

In [14]:
e = np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
np.dot(e, g)

array([[ 46.,  56.,  52.],
       [ 56.,  70.,  56.],
       [ 52.,  56., 214.]])

#### Обратная матрица
### $A \cdot A^{-1} = E$

In [16]:
p = np.linalg.inv(g)
print(p)

[[ 1.11904762 -0.85714286 -0.04761905]
 [-0.85714286  0.67460317  0.03174603]
 [-0.04761905  0.03174603  0.00793651]]


In [17]:
np.dot(g, p)

array([[ 1.00000000e+00, -6.27276009e-15, -3.74700271e-16],
       [-5.71764858e-15,  1.00000000e+00, -2.77555756e-17],
       [ 7.35522754e-16, -2.85882429e-15,  1.00000000e+00]])

In [18]:
np.dot(p, g)

array([[ 1.00000000e+00,  6.16173779e-15,  6.03683770e-15],
       [-1.15740750e-14,  1.00000000e+00, -9.64506253e-15],
       [-5.96744876e-16, -4.71844785e-16,  1.00000000e+00]])

#### Свойства сложения и умножения матриц
### $(k \cdot l) \cdot A = k \cdot (l \cdot A)$
### $k \cdot (A+B) = k \cdot A + k \cdot B $
### $(k+l) \cdot A = k \cdot A + l \cdot A $
### $(A \cdot B) \cdot C = A \cdot (B \cdot C) $
### $(A + B) \cdot C = A \cdot C + B \cdot C $
### $A \cdot (B + C) = A \cdot B + A \cdot C $