## Матричные разложения 

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg  

### Линейные системы уравнений 
## $A = \left(
\begin{array}{cccc}
a_{00} & a_{01} & \ldots & a_{0n}\\
a_{10} & a_{11} & \ldots & a_{1n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n0} & a_{n1} & \ldots & a_{nn}
\end{array}
\right) ,     X = \left(
\begin{array}{cccc}
x_0\\x_1\\\vdots\\x_{n}
\end{array}
\right)
,     B = \left(
\begin{array}{cccc}
b_0\\b_1\\\vdots\\b_{n}
\end{array}
\right)$
## $A\cdot X = B$
### LU - разложение
## $P\cdot A = L\cdot U$
## $L = \left(
\begin{array}{cccc}
l_{00} & 0 & \ldots & 0\\
l_{10} & l_{11} & \ldots & 0\\
\vdots & \vdots & \ddots & \vdots\\
l_{n0} & l_{n1} & \ldots & l_{nn}
\end{array}
\right)$
## $U = \left(
\begin{array}{cccc}
u_{00} & u_{01} & \ldots & u_{0n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \ldots & u_{n-1n}\\
0 & 0 & \ldots & u_{nn}
\end{array}
\right)$


In [2]:
A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

print(np.dot(P.transpose(), A) - np.dot(L, U))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -4.44089210e-16]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -1.11022302e-16]
 [  0.00000000e+00  -4.44089210e-16  -1.11022302e-16   0.00000000e+00]]


## $A \cdot x = L \cdot U \cdot x = b$
## $\left(
\begin{array}{cccc}
l_{00} & 0 & \ldots & 0\\
l_{10} & l_{11} & \ldots & 0\\
\vdots & \vdots & \ddots & \vdots\\
l_{n0} & l_{n1} & \ldots & l_{nn}
\end{array}
\right) \cdot  \left(
\begin{array}{cccc}
u_{00} & u_{01} & \ldots & u_{0n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \ldots & u_{n-1n}\\
0 & 0 & \ldots & u_{nn}
\end{array}
\right)\cdot 
\left(
\begin{array}{cccc}
x_0\\x_1\\\vdots\\x_{n}
\end{array}
\right) = b$

## $\left(
\begin{array}{cccc}
l_{00} & 0 & \ldots & 0\\
l_{10} & l_{11} & \ldots & 0\\
\vdots & \vdots & \ddots & \vdots\\
l_{n0} & l_{n1} & \ldots & l_{nn}
\end{array}
\right) \cdot 
\left(
\begin{array}{cccc}
y_0\\y_1\\\vdots\\y_{n}
\end{array}
\right) = b$

## $\left(
\begin{array}{cccc}
u_{00} & u_{01} & \ldots & u_{0n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \ldots & u_{n-1n}\\
0 & 0 & \ldots & u_{nn}
\end{array}
\right)\cdot 
\left(
\begin{array}{cccc}
x_0\\x_1\\\vdots\\x_{n}
\end{array}
\right) = y$


In [3]:
L = np.array([ [1, 0, 0, 0], [3, 1, 0, 0], [-1, 2, 4, 0], [2, -4, -1, 1] ])
U = np.array([ [-1, 6, 3, 6], [0, 2, -8, 2], [0, 0, 7, 3], [0, 0, 0, -1] ])
A = np.dot(L, U)
P, L, U = scipy.linalg.lu(A)

print("det A = ", np.linalg.det(A))
print("P = ", P)
print("L = ", L)
print("U = ", U)

B = np.array([4, 1, 7, 3])
np.linalg.solve(A, B)

det A =  56.0
P =  [[ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]]
L =  [[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333 -0.5         1.          0.        ]
 [ 0.33333333  0.07142857  0.02040816  1.        ]]
U =  [[ -3.          20.           1.          20.        ]
 [  0.          -9.33333333  30.33333333 -13.33333333]
 [  0.           0.          24.5         10.        ]
 [  0.           0.           0.           0.08163265]]


array([-476.71428571, -111.39285714,  -16.28571429,   40.75      ])

### Разложение Холецкого
## $A = L\cdot L^T$
## $L = \left(
\begin{array}{cccc}
l_{00} & 0 & \ldots & 0\\
l_{10} & l_{11} & \ldots & 0\\
\vdots & \vdots & \ddots & \vdots\\
l_{n0} & l_{n1} & \ldots & l_{nn}
\end{array}
\right)$

In [4]:
A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
print(A)
L = np.linalg.cholesky(A)
print(L)
print(np.transpose(L))
np.dot(L, np.transpose(L))

[[ 7  3 -1  2]
 [ 3  8  1 -4]
 [-1  1  4 -1]
 [ 2 -4 -1  6]]
[[ 2.64575131  0.          0.          0.        ]
 [ 1.13389342  2.59119388  0.          0.        ]
 [-0.37796447  0.55131785  1.88499111  0.        ]
 [ 0.75592895 -1.87448068  0.16931058  1.37339999]]
[[ 2.64575131  1.13389342 -0.37796447  0.75592895]
 [ 0.          2.59119388  0.55131785 -1.87448068]
 [ 0.          0.          1.88499111  0.16931058]
 [ 0.          0.          0.          1.37339999]]


array([[ 7.,  3., -1.,  2.],
       [ 3.,  8.,  1., -4.],
       [-1.,  1.,  4., -1.],
       [ 2., -4., -1.,  6.]])

In [5]:
A = np.array([[ 1,  2,  3],
              [ 2, 16, 21],
              [ 4, 28, 73]])