### Матричные разложения 

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## $A\cdot X = B$
## QR - разложение
## $A = Q\cdot R$

### Q - ортогональная матрица
## $Q^T \cdot Q  = I$
## $|Q \cdot X|  = |X|$
### Идея ортогональных преобразований
## $min ~|A \cdot X - B|$ 
## $min ~|Q^T \cdot (A \cdot X - B)|$
## $R = \left(
\begin{array}{cccc}
u_{00} & u_{01} & \ldots & u_{0n}\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \ldots & u_{n-1n}\\
0 & 0 & \ldots & u_{nn}
\end{array}
\right)$
### для "хороших" СЛАУ:
## $Q^T \cdot A \cdot X = Q^T \cdot B$
## $Q^T \cdot Q \cdot R \cdot X = Q^T \cdot B$
## $R \cdot X = Q^T \cdot B$
### для недоопределенных и вырожденных СЛАУ:
## $R = \left(
\begin{array}{cccc}
R_1 & R_2\\
0 & 0 \end{array}
\right)$
## $X = \left(
\begin{array}{cccc}
X_1 \\
X_2 \end{array}
\right)$
## $R_1 \cdot X_1 = Q^T \cdot B - R_2 \cdot X_2$

In [2]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([6, 12, 24])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[ -8.12403840e+00  -9.60113630e+00  -1.10782342e+01]
 [  0.00000000e+00   9.04534034e-01   1.80906807e+00]
 [  0.00000000e+00   0.00000000e+00  -8.88178420e-16]]


In [3]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[  1.00000000e+00  -2.22044605e-16   0.00000000e+00]
 [ -2.22044605e-16   1.00000000e+00   1.38777878e-17]
 [  0.00000000e+00   1.38777878e-17   1.00000000e+00]]


In [4]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [5]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-27.326311  ,   1.80906807])

In [6]:
X1 = np.linalg.solve(R1, B1)
X1

array([ 1.,  2.])

In [7]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[ 1.  2.  0.]


2.2360679774997911

In [8]:
np.linalg.norm(np.dot(A, X) - B)

2.4494897427831779

In [9]:
X = np.array([1.5, 1, 0.5])
np.linalg.norm(X),  np.linalg.norm(np.dot(A, X) - B)      

(1.8708286933869707, 2.4494897427831779)