<a href="https://colab.research.google.com/github/MoriMorou/GB_Python/blob/master/Lesson_3_P1_REVISED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Урок 3

# Матрицы и матричные операции. Часть 1

__Матрицей__ размера $m\times n$ называется прямоугольная таблица, состоящая из $m$ строк и $n$ столбцов. Элементы матрицы, обозначаемой заглавной буквой (например $A$), обычно обозначаются $a_{ij}$, где индексы $i$ и $j$ — соответственно номера строки и столбца, в которых находится элемент. 

$$\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix}$$

Числа $m$ и $n$ называют _порядками_ матрицы. Если $m=n$, то матрица называется _квадратной_, а число $m=n$ — ее _порядком_.

Для краткого обозначения матрицы иногда используется символ $\left\|a_{ij}\right\|$ или выражение $A = \left\|a_{ij}\right\| = (a_{ij}) ~ (i = 1,2,...,m; ~ j = 1,2,...,n).$

В машинном обучении матрицы обычно используются для хранения информации об объектах и их признаках. При этом обычно по строкам распологаются объекты, а по столбцам — признаки (некоторые свойства объектов, значения которых используются для обучения модели и которые затем эта модель должна предсказывать для других объектов).

Векторы, изученные в предыдущих уроках, являются частными случаями матриц: в частности, упомянутые в предыдущем уроке _вектор-строка_ (матрица размера $1\times m$) и _вектор-столбец_ (матрица размера $n\times1$):

$$\begin{pmatrix}
1 & 2 & 3
\end{pmatrix} ~ и ~ \begin{pmatrix}
1\\ 
2\\ 
3
\end{pmatrix}.$$

В Python работа с матрицами обычно ведется при помощи библиотеки NumPy.

In [0]:
import numpy as np

Самый простой способ создать матрицу — с помощью функции `numpy.array(list, dtype=None, ...)`. Здесь `list` — список итерируемых объектов, которые составят строки матрицы. Мы уже использовали эту функцию в первом уроке для создания векторов (частный одномерный случай матриц).

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Матричные операции

### 1. Сложение матриц

Рассмотрим матрицы $A$ размера $m\times n$, состоящую из элементов $a_{ij}$, и $B$ того же размера, состоящую из элементов $b_{ij}$.

Складывать можно только __матрицы одинаковых порядков__, и сложение их происходит поэлементно, то есть _суммой_ двух матриц $A+B$ будет являться матрица $C$ того же размера, состоящая из элементов $c_{ij}=a_{ij}+b_{ij}$:

$$A + B = 
\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix} + \begin{pmatrix}
b_{11} & b_{12} & \cdots & b_{1n}\\ 
b_{21} & b_{22} & \cdots & b_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
b_{m1} & b_{m2} & \cdots & b_{mn}\\ 
\end{pmatrix} = \begin{pmatrix}
a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n}\\ 
a_{21} + b_{21}& a_{22} + b_{22}& \cdots & a_{2n} + b_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn}\\ 
\end{pmatrix}
= C.$$

__Пример__

Сложим две матрицы, заполненные натуральными числами:

$$\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix} + \begin{pmatrix}
1 & 1 & 1\\ 
1 & 1 & 1\\ 
1 & 1 & 1
\end{pmatrix} = \begin{pmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{pmatrix}.$$


И проведем ту же операцию при помощи Python:

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.ones((3,3))  # функция для создания матрицы размера (x,y), заполненной единицами

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')

Матрица A
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Матрица С = A + B
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


Операция сложения матриц обладает теми же свойствами, что и операция сложения вещественных чисел, а именно:<br>
1) переместительным свойством: $A+B=B+A;$<br>
2) сочетательным свойством: $(A+B)+C=A+(B+C).$

### 2. Умножение матриц на число

Умножение матрицы на число происходит так же просто, как и сложение: _произведением матрицы_ $A=\left\|a_{ij}\right\|$ на число $\lambda$ является матрица $C = \left\|c_{ij}\right\|$, элементы которой $c_{ij}=\lambda a_{ij}$, то есть каждый элемент матрицы умножается на число $\lambda$:

$$\lambda\cdot\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
a_{21} & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{m1} & a_{m2} & \cdots & a_{mn}\\ 
\end{pmatrix}=
\begin{pmatrix}
\lambda a_{11} & \lambda a_{12} & \cdots & \lambda a_{1n}\\ 
\lambda a_{21} & \lambda a_{22} & \cdots & \lambda a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
\lambda a_{m1} & \lambda a_{m2} & \cdots & \lambda a_{mn}\\ 
\end{pmatrix}.$$

__Пример__

$$3\cdot\begin{pmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{pmatrix} = \begin{pmatrix}
3 & 6 & 9\\ 
12 & 15 & 18\\ 
21 & 24 & 27
\end{pmatrix}.$$


Так же это происходит и в Python:

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
k = 3

print(f'Матрица А\n{a}\n')
print(f'Матрица 3*А\n{k*a}')

Матрица А
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица 3*А
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


Умножение матрицы на число обладает следующими свойствами:<br>
1) $(\lambda \mu)A=\lambda(\mu A);$<br>
2) $\lambda (A+B)=\lambda A + \lambda B;$<br>
3) $(\lambda + \mu) A = \lambda A + \mu A.$

### 3. Перемножение матриц

_Произведением_ матрицы $A = \left\|a_{ij}\right\|$, имеющей порядки $m$ и $n$, и матрицы $B = \left\|b_{ij}\right\|$, имеющей порядки $n$ и $k$, называется матрица $C = \left\|c_{ij}\right\|$, имеющая порядки $m$ и $k$:

$$C = \begin{pmatrix}
c_{11} & c_{12} & \cdots & c_{1k}\\ 
c_{21} & c_{22} & \cdots & c_{2k}\\ 
\cdots & \cdots & \ddots & \cdots\\ 
c_{m1} & c_{m2} & \cdots & c_{mk}
\end{pmatrix},$$

наполненная элементами, определяемыми формулой

$$ c_{ij}=\sum_{p=1}^{n}a_{ip}b_{pj}.$$

Правило перемножения матриц можно сформулировать словесно следующим образом: _элемент $c_{ij}$, стоящий на пересечении $i$-й строки и $j$-го столбца матрицы $C=A\cdot B$, равен сумме попарных произведений соответствующих элементов $i$-й строки матрицы $A$ и $j$-го столбца матрицы $B$._

Следует заметить, что матрицу $A$ можно умножить не на всякую матрицу $B$: __необходимо, чтобы число столбцов матрицы $A$ было равно числу строк матрицы $B$.__

В частности, определить оба произведения $A\cdot B$ и $B\cdot A$ можно только в случае, когда число столбцов $A$ совпадает с числом строк $B$, а число строк $A$ совпадает с числом столбцов $B$. В этом случае матрицы $A\cdot B$ и $B\cdot A$ будут квадратными. Их порядок в общем случае будет различным и будет совпадать только в случае квадратных матриц $A$ и $B$.

__Пример 1__

Скалярное произведение векторов, рассмотренное нами на предыдущем уроке, можно понимать как умножение вектора-строки на вектор-столбец.

__Пример 2__

Для лучшего понимания рассмотрим в качестве примера перемножение квадратных матриц второго порядка:

$$\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix} \begin{pmatrix}
b_{11} & b_{12}\\ 
b_{21} & b_{22}
\end{pmatrix}=\begin{pmatrix}
(a_{11}b_{11} + a_{12}b_{21}) & (a_{11}b_{12} + a_{12}b_{22})\\ 
(a_{21}b_{11} + a_{22}b_{21}) & (a_{21}b_{12} + a_{22}b_{22})
\end{pmatrix}.$$

__Пример 3__

Перемножим матрицы 

$$A=\begin{pmatrix}
1 & 0\\ 
2 & 1\\ 
10 & 5
\end{pmatrix} \; и \; B=\begin{pmatrix}
2 & 0 & 0\\ 
0 & 0 & 1
\end{pmatrix}.$$

$$A\cdot B=\begin{pmatrix}
1\cdot2+0\cdot0 & 1\cdot0+2\cdot0 & 1\cdot0+0\cdot1\\ 
2\cdot2+1\cdot0 & 2\cdot0+1\cdot0 & 2\cdot0+1\cdot1\\ 
10\cdot2+5\cdot0 & 10\cdot0+5\cdot0 & 10\cdot0+5\cdot1
\end{pmatrix}=\begin{pmatrix}
2 & 0 & 0\\ 
4 & 0 & 1\\ 
20 & 0 & 5
\end{pmatrix}.$$

Сделаем то же самое при помощи Python.

В библиотеке NumPy перемножение матриц осуществляется при помощи тех же инструментов, которые мы использовали для нахождения скалярного произведения векторов, — функции `numpy.dot(a, b)` или метода `a.dot(b)`, только в этом случае `a` и `b` — матрицы.

In [0]:
A = np.array([[1, 0], [2, 1], [10, 5]])
B = np.array([[2, 0, 0], [0, 0, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1  0]
 [ 2  1]
 [10  5]]
Матрица B
[[2 0 0]
 [0 0 1]]
Матрица AB
[[ 2  0  0]
 [ 4  0  1]
 [20  0  5]]


Попробуем перемножить матрицы, не отвечающие правилу соответствия количества строк и столбцов:

In [0]:
A = np.array([[1, 0], [2, 1], [10, 5]])
B = np.array([[2, 0, 0], [0, 0, 1], [0, 0, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1  0]
 [ 2  1]
 [10  5]]
Матрица B
[[2 0 0]
 [0 0 1]
 [0 0 1]]


ValueError: shapes (3,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

Запуск кода в ячейке выше приводит к ошибке, так как количество столбцов первой матрицы не равно количеству строк второй при перемножении.

__Пример 4__

Перемножим матрицы

$$A = \begin{pmatrix}
1 & 3\\ 
2 & 6
\end{pmatrix} ~ 
и ~
B = \begin{pmatrix}
9 & 6\\ 
-3 & -2
\end{pmatrix}.$$

$$\begin{pmatrix}
1 & 3\\ 
2 & 6
\end{pmatrix} \cdot
\begin{pmatrix}
9 & 6\\ 
-3 & -2
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 9 + 3\cdot (-3) & 1\cdot6 + 3\cdot (-2)\\ 
2\cdot 9 + 6\cdot (-3) & 2\cdot6 + 6\cdot (-2)
\end{pmatrix} = 
\begin{pmatrix}
0 & 0\\ 
0 & 0
\end{pmatrix}.
$$

Это важный пример, показывающий наличие среди матриц делителей нуля, т. е. ненулевых матриц, при перемножении дающих _нулевую матрицу_.

Из специфики произведения матриц следует, что оно не обладает свойством коммутативности, то есть $AB\neq BA$. В общем случае это справедливо даже для квадратных матриц, например:

$$\begin{pmatrix}
0 & 0\\ 
0 & 1
\end{pmatrix} \begin{pmatrix}
0 & 0\\ 
1 & 0
\end{pmatrix}=\begin{pmatrix}
0 & 0\\ 
1 & 0
\end{pmatrix},$$
$$\begin{pmatrix}
0 & 0\\ 
1 & 0
\end{pmatrix}\begin{pmatrix}
0 & 0\\ 
0 & 1
\end{pmatrix}=\begin{pmatrix}
0 & 0\\ 
0 & 0
\end{pmatrix}.$$


Однако произведению матриц __подходящих размеров__ свойственны другие особенности:

1. Ассоциативность: $(AB)C = A(BC).$

   __Доказательство__

    Возьмем матрицы $A$ размера $m\times n$, $B$ размера $n\times k$, $C$ размера $k\times l$. Тогда, по определению $i,j$-й элемент произведения матрицы $AB$ на матрицу $C$ равен:

    $$\left\{(AB)C\right\}_{ij}=\sum_{p=1}^{k}\left\{AB\right\}_{ip}c_{pj}=\sum_{p=1}^{k}\left        
    (\sum_{q=1}^{n}a_{iq}b_{qp}\right)c_{pj}=\sum_{q=1}^{n}a_{iq}\left(\sum_{p=1}^{k}b_{qp}c_{pj}\right)=\left\{A(BC)\right\}_{ij},$$

    что и требовалось доказать.


2. Дистрибутивность: $(A+B)C = AC + BC$ и $A(B+C) = AB + AC$.

    Это свойство вытекает из определений суммы и произведения матриц.

__Возведение матриц в степень__ является частным случаем перемножения:

$$A\cdot A = A^{2}.$$

__Пример__

$$\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix}^{2} = 
\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix} \cdot
\begin{pmatrix}
1 & 1\\ 
0 & 1
\end{pmatrix} = 
\begin{pmatrix}
1\cdot1 + 1\cdot0 & 1\cdot1 + 1\cdot1\\ 
0\cdot1 + 1\cdot0 & 0\cdot1 + 1\cdot1
\end{pmatrix} = 
\begin{pmatrix}
1 & 2\\ 
0 & 1
\end{pmatrix}
$$

### 4. Транспонирование матриц

Рассмотрим еще одну распространенную процедуру при работе с матрицами, называемую _транспонированием._

Пусть имеется матрица $A$ размера $m\times n$. В таком случае матрица $B$, полученная транспонированием матрицы $A$ и обозначаемая $B=A^{T}$, будет представлять собой матрицу размера $n\times m$, элементы которой $b_{ij}=a_{ji}$. Иными словами, транспонированная матрица — это матрица, отраженная относительно главной диагонали (диагональ, на которой распологаются элементы с $i=j$). При транспонировании строки исходной матрицы становятся столбцами, а столбцы — строками.

__Пример__

$$A=\begin{pmatrix}
8 & 5 & 3\\ 
4 & 6 & 1\\ 
0 & 11 & 9\\ 
2 & 7 & 10
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
8 & 4 & 0 & 2\\ 
5 & 6 & 11 & 7\\ 
3 & 1 & 9 & 10
\end{pmatrix}.$$

В NumPy транспонированная матрица вычисляется с помощью функции `numpy.transpose(array)` или с помощью метода `array.T`, где `array` — матрица.

In [0]:
a = np.array([[8, 5, 3], [4, 6, 1], [0, 11, 9], [2, 7, 10]])

print(f'Матрица:\n{a}')
print(f'Транспонированная матрица:\n{a.T}')

Матрица:
[[ 8  5  3]
 [ 4  6  1]
 [ 0 11  9]
 [ 2  7 10]]
Транспонированная матрица:
[[ 8  4  0  2]
 [ 5  6 11  7]
 [ 3  1  9 10]]


Некоторые важные свойства транспонирования:<br>
1) $(A+B)^{T}=A^{T}+B^{T};$<br>
2) $(A\cdot B)^{T}=B^{T}\cdot A^{T}.$

## Типы матриц

Рассмотрим некоторые особые типы матриц, которые понадобятся нам в будущем, в частности, при рассмотрении темы линейных преобразований и матричных разложений.

### Диагональная матрица

_Диагональная матрица_ — матрица, в которой все элементы, не лежащие на главной диагонали, — нулевые:

$$D = \begin{pmatrix}
d_{1} & 0 & \cdots & 0\\ 
0 & d_{2} & \cdots  & 0\\ 
\cdots & \cdots & \ddots & \cdots\\ 
0 & 0 & \cdots & d_{n}
\end{pmatrix}.$$

Частным случаем диагональной матрицы является _единичная матрица_, обычно обозначаемая $E$ или $I$ — это матрица, в которой главную диагональ занимают единицы, а остальные элементы — нулевые:

$$E=\begin{pmatrix}
1 & 0 & \cdots & 0\\ 
0 & 1 & \cdots  & 0\\ 
\cdots & \cdots & \ddots & \cdots\\ 
0 & 0 & \cdots & 1
\end{pmatrix}.$$


В NumPy единичная матрица задается при помощи функции `numpy.eye(n)`, где `n` — порядок матрицы:

In [0]:
e = np.eye(5)
print(f'Единичная матрица:\n{e}')

Единичная матрица:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Треугольная матрица

_Треугольная матрица_ — квадратная матрица, у которой все элементы, стоящие ниже (или выше) главной диагонали — нулевые.

Треугольная матрица, у которой все элементы ниже главной диагонали равны нулю, называется _верхней треугольной (верхне-треугольной)_ матрицей:

$$\begin{pmatrix}
a_{11} & a_{12} & \cdots & a_{1n}\\ 
0 & a_{22} & \cdots & a_{2n}\\  
\cdots & \cdots & \ddots & \cdots \\ 
0 & 0 & \cdots & a_{nn}\\ 
\end{pmatrix}.$$

Треугольная матрица, у которой все элементы выше главной диагонали равны нулю, называется _нижней треугольной (нижне-треугольной)_ матрицей:

$$\begin{pmatrix}
a_{11} & 0 & \cdots & 0\\ 
a_{21} & a_{22} & \cdots & 0\\  
\cdots & \cdots & \ddots & \cdots \\ 
a_{n1} & a_{n2} & \cdots & a_{nn}\\ 
\end{pmatrix}.$$

Важное свойство верхне-треугольных матриц: _при перемножении верхне-треугольных матриц свойство верхней треугольности сохраняется._

__Пример__

In [0]:
a = np.array([[1, 2, 3, 5, 6], [0, 5, 6, 3, 1], [0, 0, 9, 7, 4], [0, 0, 0, 2, 4], [0, 0, 0, 0, 6]])
b = np.array([[1, 2, 3, 7, 1], [0, 8, 8, 5, 3], [0, 0, 5, 7, 9], [0, 0, 0, 7, 4], [0, 0, 0, 0, 2]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица AB\n{np.dot(a, b)}')

Матрица A
[[1 2 3 5 6]
 [0 5 6 3 1]
 [0 0 9 7 4]
 [0 0 0 2 4]
 [0 0 0 0 6]]

Матрица B
[[1 2 3 7 1]
 [0 8 8 5 3]
 [0 0 5 7 9]
 [0 0 0 7 4]
 [0 0 0 0 2]]

Матрица AB
[[  1  18  34  73  66]
 [  0  40  70  88  83]
 [  0   0  45 112 117]
 [  0   0   0  14  16]
 [  0   0   0   0  12]]


### Ортогональная матрица

Матрица $A$ называется _ортогональной_, если 

$$AA^{T}=A^{T}A=E.$$

__Пример__

Ортогональной является матрица

$$\begin{pmatrix}
cos\varphi & -sin\varphi\\ 
sin \varphi & cos\varphi
\end{pmatrix}.$$

Убедимся, что это действительно так:

$$\begin{pmatrix}
cos\varphi & -sin\varphi\\ 
sin \varphi & cos\varphi
\end{pmatrix} \cdot 
\begin{pmatrix}
cos\varphi & sin\varphi\\ 
-sin \varphi & cos\varphi
\end{pmatrix} = 
\begin{pmatrix}
cos\varphi \cdot cos\varphi + (-sin\varphi) \cdot (-sin\varphi) & cos\varphi \cdot sin\varphi + (-sin\varphi) \cdot cos\varphi\\ 
sin\varphi \cdot cos\varphi + cos\varphi \cdot (-sin\varphi) & sin\varphi \cdot sin\varphi + cos\varphi \cdot cos\varphi
\end{pmatrix} = 
\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix}.$$

### Симметричная матрица

Матрица $A$ называется _симметричной_, если

$$A=A^{T},$$

то есть симметричная матрица симметрична относительно главной диагонали.

## Практическое задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

## Литература

1. Ильин В. А., Позняк Э. Г. Линейная алгебра: Учеб. для вузов. — 6-е изд. — М.: Физматлит, 2005.


## Дополнительные материалы

1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).